---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: window
  labels:
    app: window
spec:
  replicas: 1
  selector:
    matchLabels:
      app: window
  template:
    metadata:
      labels:
        app: window
    spec:
      containers:
        - name: window
          image: username/window:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: work
  labels:
    app: work
spec:
  replicas: 1
  selector:
    matchLabels:
      app: work
  template:
    metadata:
      labels:
        app: work
    spec:
      containers:
        - name: work
          image: username/work:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: window
  labels:
    app: window
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: window


---


apiVersion: v1
kind: Service
metadata:
  name: work
  labels:
    app: work
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: work

